server:
    http_listen_port: 9080
    grpc_listen_port: 0
    log_level: "info"

positions:
    filename: /var/lib/promtail/positions.yaml

clients:
    - url: http://loki-gateway:80/loki/api/v1/push
      tenant_id: docker

scrape_configs:
  # Docker容器日志采集 - 使用Docker socket
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock    # Docker socket路径
        refresh_interval: 5s                 # 5秒刷新一次容器列表
    relabel_configs:
      # 先排除 Claude Relay Service（避免与专用任务重复采集）
      - action: drop
        source_labels: ['__meta_docker_container_image']
        regex: '(.*/)?claude-relay-service(:.*)?'
      # 将容器日志文件路径映射到 __path__，让 promtail 直接跟随 json-file 日志
      - action: replace
        source_labels: ['__meta_docker_container_log_path']
        target_label: '__path__'
      # 固定添加 job 标签（使用 replace + source 以确保生效）
      - action: replace
        source_labels: ['__meta_docker_container_id']
        target_label: 'job'
        replacement: 'docker'
      - source_labels: ['__meta_docker_container_name']
        target_label: 'container_name'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'logstream'
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: 'service'
      - source_labels: ['__meta_docker_container_label_com_docker_compose_project']
        target_label: 'project'
    pipeline_stages:
      # 直接解析 Docker 默认 json-file 格式，更稳健
      - docker: {}
      - labels:
          stream:
          container_name:
          service:
          project:

  # 采集 Claude Relay Service 的文件日志
  - job_name: claude-relay-service
    static_configs:
      - targets:
          - localhost
        labels:
          job: claude-relay-service
          __path__: /opt/aicoding/crs/logs/*.log

  # 保留原有的生成器日志采集
  - job_name: generated-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: generated-logs
          __path__: /var/log/generated-logs.txt
    pipeline_stages:
      - json:
          expressions:
            http_method: 'method'
            http_status: "status"
      - labels:
          http_method:
          http_status:
  
