server:
    http_listen_port: 9080
    grpc_listen_port: 0
    log_level: "info"

positions:
    filename: /tmp/positions.yaml

clients:
    - url: http://loki-gateway:80/loki/api/v1/push
      tenant_id: docker

scrape_configs:
  # Docker容器日志采集 - 使用Docker socket
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock    # Docker socket路径
        refresh_interval: 5s                 # 5秒刷新一次容器列表
        filters:                             # 过滤器
          - name: label
            values: ["logging=promtail"]      # 只采集带此标签的容器
    relabel_configs:
      # 重标记配置
      - source_labels: ['__meta_docker_container_name']
        target_label: 'container_name'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'logstream'
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: 'service'
      - source_labels: ['__meta_docker_container_label_com_docker_compose_project']
        target_label: 'project'
    pipeline_stages:
      # 日志处理管道
      - json:
          expressions:
            output: 'output'
            stream: 'stream'
            timestamp: 'timestamp'
      - timestamp:
          source: timestamp
          format: RFC3339Nano
      - labels:
          stream:
          container_name:
          service:
          project:

  # 保留原有的生成器日志采集
  - job_name: generated-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: generated-logs
          __path__: /var/log/generated-logs.txt
    pipeline_stages:
      - json:
          expressions:
            http_method: 'method'
            http_status: "status"
      - labels:
          http_method:
          http_status:
